run:
	# Test 1:
	python3 sabre.py -a CustomAbr.py -r CustomReplacement.py -n network.json
	#
	# Test 2:"
	python3 sabre.py -a CustomAbr.py -r CustomReplacement.py -n network2.json
	#
	# Test 3:
	python3 sabre.py -a CustomAbr.py -r CustomReplacement.py -n network3.json